Add SEE LESS button to 2020 ScholarX mentor's section
sef-global/sef-site pull request #1032
Opened 2021-07-18 04:17 UTC by gajindubandara

## Purpose

The purpose of this PR is to fix #1031

## Goals
To add the SEE LESS button to the 2020 ScholarX mentor's section

## Approach
Added the SEE LESS button to the 2020 ScholarX mentor's section
 

### Screenshots
![Screenshot from 2021-07-18 09-46-13](https://user-images.githubusercontent.com/63200586/126055495-6f50dd9e-d277-4a54-a24b-2aca48114b3a.png)

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-07-18 15:49 UTC, janethavi requested changes
Great work @gajindubandara! Is it possible to add the scroll-up functionality as well? When the `show less` button is clicked it will automatically scroll up to the beginning of the mentor's section? You can look into this [PR](https://github.com/sef-global/sef-site/pull/1033) to get an idea if you want.

2021-07-19 06:16 UTC, gajindubandara commented
> Great work @gajindubandara! Is it possible to add the scroll-up functionality as well? When the `show less` button is clicked it will automatically scroll up to the beginning of the mentor's section? You can look into this [PR](https://github.com/sef-global/sef-site/pull/1033) to get an idea if you want.

Yeah! I'll do that

2021-07-20 05:20 UTC, janethavi approved these changes
Great work! @gajindubandara

2021-07-20 20:26 UTC, Piumal1999 approved these changes
Well done. Thank you @gajindubandara

2021-07-21 03:35 UTC, merged