Replace team page images with Cloudinary URLs
sef-global/sef-site pull request #1052
Opened 2021-07-25 09:55 UTC by akeel230

## Purpose
Replace ScholarX 2019 mentor's images with Cloudinary URLs fix #1048 

## Goals
Replace ScholarX 2019 mentor's images with Cloudinary URLs

## Approach
Copy image URLs in issue #1048  to spreadsheet and update link in index.html

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
#1041
#1042
#1045
#1051

## Test environment
 

## Learning

2021-07-25 13:06 UTC, janethavi requested changes
Looks like the Purpose and the Goal description are different than the PR header(PR header is correct).

2021-07-25 14:08 UTC, akeel230 commented
@janethavi Sorry my bad. edited. Thanks for the feedback

2021-07-25 16:28 UTC, Piumal1999 approved these changes
Good job! @akeel230

2021-07-26 03:42 UTC, janethavi approved these changes
Great work @akeel230!

2021-07-26 03:43 UTC, merged