Add preloaders to ScholarX 2020 & 2019 mentee's section
sef-global/sef-site pull request #1097
Opened 2021-08-23 07:43 UTC by VWRoli

## Purpose

The purpose of this PR is to fix #1094 

## Goals

Add skeleton preloader to ScholarX 2020 & 2019 mentee's section

## Approach

Inserted skeleton HTML code, to the appropriate sections

### Screenshots

![Screenshot from 2021-08-23 09-41-18](https://user-images.githubusercontent.com/31432331/130409454-19b54fac-140e-44b1-832d-eb06617c983c.png)
  

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
#1092 

## Test environment
 
Linux, Brave, Chrome

2021-09-03 13:38 UTC, janethavi approved these changes, later dismissed
Good work!

2021-10-07 19:05 UTC, Piumal1999 requested changes

2021-10-07 19:05 UTC, Piumal1999 commented on scholarx/archive/2019/index.html
> +                    <th scope="col">View Blog Article</th>
'View blog article' option is not there in the ScholarX 2019 table. Remove it and add 'Mentor' as that table header.

Also it creates another header row after loading. 
![image](https://user-images.githubusercontent.com/27498587/136446461-f6fd7009-c725-409b-aa3d-3244192ebf0e.png)

You can fix that by removing the duplicate parts in the mustache template.

```
<table class="table table-striped">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Name</th>
            <th scope="col">University</th>
            <th scope="col">Mentor</th>
          </tr>
        </thead>
```

2021-10-08 07:33 UTC, fustroli commented on scholarx/archive/2019/index.html
> +                    <th scope="col">View Blog Article</th>
Requested changes are done.
![Screenshot from 2021-10-08 09-32-27](https://user-images.githubusercontent.com/31432331/136516503-14bae4d5-a95a-4dca-9ec9-9625f4f57d23.png)

2021-10-08 11:07 UTC, Piumal1999 requested changes
Hi @VWRoli, I added some comments and suggestions. Could you please check those and update the pull request? Sorry for bothering you

2021-10-08 11:07 UTC, Piumal1999 commented on scholarx/archive/2020/index.html
> +                    <th scope="col">View Blog Article</th>
Here also, it should be 'Mentor'. Not 'View Blog Article'

2021-10-08 11:07 UTC, Piumal1999 commented on scholarx/archive/2019/index.html
>  <script type="text/html" id="templateMentees">
Let's update the mentee template like this:

```
<script type="text/html" id="templateMentees">
    {{#data}}
        <tr onclick="window.location='{{linkedin}}';">
            <th scope="row">
                <img src="https://res.cloudinary.com/dsxobn1ln/image/upload/c_scale,h_48,w_48/{{image}}" class="avatar">
            </th>
                <td>{{name}}</td>
                <td>{{university}}</td>
                <td>{{mentor}}</td>
        </tr>
    {{/data}}     
</script>
```

2021-10-08 11:07 UTC, Piumal1999 commented on scholarx/archive/2019/index.html
>  <script type="text/html" id="templateMentees">
That's how it is done on the scholarx/archive/2020/index.html page

2021-10-08 11:54 UTC, fustroli commented on scholarx/archive/2019/index.html
>  <script type="text/html" id="templateMentees">
> Hi @VWRoli, I added some comments and suggestions. Could you please check those and update the pull request? Sorry for bothering you

No worries @Piumal1999.  Fixed the things you asked.

2021-10-08 14:17 UTC, Piumal1999 commented on scholarx/archive/2019/index.html
> +                    <th scope="col">View Blog Article</th>
Well done! Thank you @VWRoli

2021-10-08 14:18 UTC, Piumal1999 approved these changes

2021-10-08 17:31 UTC, merged