Update the fellowship API request url
sef-global/sef-site pull request #1144
Opened 2021-11-26 15:53 UTC by Madhawa97

## Purpose
The purpose of this PR is to fix #1142 

## Goals
Update the ajax request URL and get the fellowship certificates working 

## Approach
Updated the URLs according to the instructions given in #1142 

### Preview Link
https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Google Chrome Version 96.0.4664.55 (Official Build) (arm64)

2021-11-26 16:10 UTC, Piumal1999 commented
The problem is with the API. The browser doesn't load it because the request URL is `http`. We haven't got an SSL certificate for the backend domain. I'll fix that and let you know.

2021-11-26 16:35 UTC, Piumal1999 requested changes
I added the SSL certificate to the backend server. @Madhawa97 just change the URL to `https`. Now it will work

2021-11-26 16:35 UTC, Piumal1999 commented on fellowship/index.html
> +          url: 'http://apps.sefglobal.org/core/fellowship/certificates/' + id,
```suggestion
          url: 'https://apps.sefglobal.org/core/fellowship/certificates/' + id,
```

2021-11-27 13:54 UTC, Madhawa97 commented
It still gives me the same error though (403)

2021-11-27 14:30 UTC, Piumal1999 approved these changes
There was an error with the server. Now it's working. Good Job! @Madhawa97 Thank you

Note: Disable CORS restrictions when using the preview link. The backend is only allowing the `sefglobal.org` origin

2021-11-28 03:47 UTC, gajindubandara approved these changes
Thank you! @Madhawa97

2021-11-28 10:40 UTC, merged