Add colored indicator to timeline
sef-global/sef-site pull request #1208
Opened 2022-08-07 01:36 UTC by DilinaBandara

## Purpose

The timeline of the ScholarX page does not have an indicator to specify the current timeline date #<1202>

## Goals
To add a colored indicator to the timeline of the page

## Approach
Added color to the present timeline date of the ScholarX process

### Screenshots
![image](https://user-images.githubusercontent.com/104125359/183271285-bfc80aac-bc4c-4ed5-b0a5-32012af2f0d5.png)

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-08-07 04:52 UTC, anjula-sack requested changes
Good job! @DilinaBandara Can you remove that unwanted file?

2022-08-07 04:52 UTC, anjula-sack commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
Remove this file

2022-08-07 13:36 UTC, DilinaBandara commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
@anjula-sack Thanks, I removed it

2022-08-08 03:36 UTC, anjula-sack approved these changes
Good job! @DilinaBandara

2022-08-08 03:37 UTC, merged