Create SEF dummy dev page
sef-global/sef-site pull request #1218
Opened 2022-08-13 12:59 UTC by RandilaP

## Purpose

The purpose of this PR is to add a new page for SEF engineering team.

## Goals
- Introduce engineering team
- Show projects done by team.

## Approach
- Add a description
- Add a projects section

### Screenshots
[Screencast from 2022-08-13 18:28:02.webm](https://user-images.githubusercontent.com/106733522/184495252-f8157284-9373-4d64-b134-ef008ff212c9.webm)

2022-08-14 03:19 UTC, jayasanka-sack commented on devpage.html
> +
```suggestion
```

2022-08-14 03:20 UTC, jayasanka-sack commented on devpage.html
> +                            <button class="btn btn-success " href="examples"><i class="fab fa-github pr-2"></i>View In github</button>
```suggestion
                        <a target="_blank"  href=" https://github.com/sef-global/sef-core
                        ">
                            <button class="btn btn-success " href="examples"><i class="fab fa-github pr-2"></i>View In github</button>
```

2022-08-14 03:20 UTC, jayasanka-sack commented on devpage.html
> +
```suggestion
```

2022-08-14 03:21 UTC, jayasanka-sack commented on devpage.html
> +</html>
```suggestion
</html>

```

2022-08-14 03:29 UTC, jayasanka-sack commented on devpage.html
> +                                <a target="_blank"  href="https://sef-scholarx.herokuapp.com/
```suggestion
                                <a target="_blank" href="https://sef-scholarx.herokuapp.com/ 
```

2022-08-14 03:32 UTC, jayasanka-sack commented
General comments: 

- [ ] View in github should be `btn-default` button. 
- [ ] The open project should be`btn-outline-default` button. 
- [ ] Use [this icon](https://fontawesome.com/v4/icon/external-link) for the open project button 
- [ ] Reduce the space between the two buttons
- [ ] Increase the width of the project description. (maybe 4 columns for logo, 8 for the description)
- [ ] Remove unwanted spaces

2022-08-14 06:55 UTC, RandilaP commented
Ok

2022-08-27 13:13 UTC, anjula-sack commented
@RandilaP There's an unwanted image. can you remove it?

2022-08-27 13:16 UTC, anjula-sack commented
@RandilaP can you find a suitable image from [freepik](https://www.freepik.com/free-photos-vectors/development). @jayasanka-sack We had a premium account, right?

2022-08-30 15:51 UTC, anjula-sack commented
> Being part of the SEF engineering team is a lot more than making a pull request. You get first-hand experience in handling the latest cutting-edge technologies and it will be required of you to develop skills that are essential to being part of the modern industry. With our community being active through various mediums such as standup meetings, knowledge-sharing sessions and communication platform groups, you will soon be exposed to the startup culture, and the various practices and procedures involved with contributing to projects.

Here's the description @RandilaP.

2022-08-31 01:14 UTC, RandilaP commented
@anjula-sack Thank you.

2022-09-03 15:55 UTC, jayasanka-sack commented on assets/content/static/navbar.html
> +                        <a href="https://handbook.sefglobal.org" target="_blank" class="nav-link" role="button">
```suggestion
                    <a href="https://handbook.sefglobal.org" target="_blank" class="nav-link" role="button">
```

2022-09-03 16:10 UTC, anjula-sack commented
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/43912578/188279039-8dc1f5e7-c75e-47e9-9c76-24846a891cd1.png">
can you fix the navbar? @RandilaP

2022-09-03 16:24 UTC, jayasanka-sack commented
I think we have too many items on the navbar. We need to remove one. What can we do?

2022-09-03 16:31 UTC, jayasanka-sack commented
One thing we should do is remove unnecessary social media icons.
We can keep only facebook, twitter and LinkedIn icons. (Other icons don't give much value, and people can't recognize them by looking at those icons. Especially slack and discourse) 

Also, we need to remove one menu item.

2022-09-03 16:37 UTC, jayasanka-sack commented
Let's make the Team menu to -> `Teams` and make it a dropdown.
There will be two sub-menu items

1. Engineering team
2. Meet the team (That points to the teams.html page) (Someone please suggest a good name for this menu item @akshika47  @anjula-sack @Piumal1999 )

Meanwhile, @RandilaP rename `devpage.html` to `engineering-team.html`

2022-09-03 16:48 UTC, RandilaP commented
@jayasanka-sack Okay.

2022-09-03 16:58 UTC, anjula-sack commented
> One thing we should do is remove unnecessary social media icons. We can keep only facebook, twitter and LinkedIn icons. (Other icons don't give much value, and people can't recognize them by looking at those icons. Especially slack and discourse)
> 
> Also, we need to remove one menu item.

I think we better keep the slack at least. People know the slack icon.

2022-09-03 17:03 UTC, jayasanka-sack commented
> I think we better keep the slack at least. People know the slack icon.

Maybe we can place them in the footer. The navbar should contain only the links users often visit or requires attention.

2022-09-04 05:43 UTC, anjula-sack commented
> Member

yeah we can keep them in the footer

2022-09-04 05:46 UTC, akshika47 commented
Hi, @jayasanka-sack I don't think the Engineering should go as a seperate team, as everyone belongs together in the SEF team. Our Engineering 'practice' would be ideal for sitting under our programs (I rephrased it as initiatives). Let me know what you think?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/4003135/188299390-f7746247-c66d-43b8-aee9-6678ac1c61c3.png">

2022-09-04 05:49 UTC, jayasanka-sack commented
Yeah, that makes sense. I love the way you have structured the menu. 
@RandilaP Shall we update it?

2022-09-04 06:11 UTC, RandilaP commented
@jayasanka-sack Okay.

2022-09-11 03:07 UTC, anjula-sack commented
Any updates? @RandilaP Do you need any help?

2022-09-30 17:09 UTC, RandilaP commented
@jayasanka-sack Can u check this

2022-10-01 02:15 UTC, RandilaP commented
@jayasanka-sack @anjula-sack Can u review this.

2022-10-01 03:05 UTC, anjula-sack requested changes, later dismissed
Good job! @RandilaP 

One small change.

<img width="107" alt="image" src="https://user-images.githubusercontent.com/43912578/193384032-26961e28-b5ce-47dc-8e0d-4d7d8060b24c.png">
This needs to be changed to `Initiatives`

and make your PR ready for review as well

2022-10-01 04:44 UTC, jayasanka-sack requested changes

2022-10-01 04:44 UTC, jayasanka-sack commented on devpage.html
> +                            </a>
```suggestion
                            <a href="https://github.com/sef-global/scholarx" class="btn btn-default" target="_blank" >
                                <i class="fab fa-github pr-2"></i>View in github
                            </a>
```

2022-10-01 13:56 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @RandilaP !

2022-10-01 13:58 UTC, merged