Decrease text size in mobile - Success stories page
sef-global/sef-site pull request #1245
Opened 2022-10-02 15:56 UTC by DilinaBandara

## Purpose

The purpose of this PR is to fix #1233 

## Goals

The goal is to decrease the size of the subparagraph on the success stories page

## Approach

Decreased text size in the CSS page
  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2022-10-03 06:06 UTC, DilinaBandara commented
Can you take a look at this, please? @anjula-sack

2022-10-03 07:56 UTC, anjula-sack commented
There are some conflicts @DilinaBandara. can you resolve them?

2022-10-03 10:52 UTC, Piumal1999 reviewed
@DilinaBandara Next time when you create a new branch, make sure the local main branch is up to date with the main branch of the sefglobal/sef-site repo. So you can avoid getting unwanted commits in the pull request.

```
git checkout main
git reset --hard upstream/main   (optional)
git pull upstream main
git checkout -b my-new-branch
// do the changes, commit and push
```

2022-10-03 10:57 UTC, Piumal1999 requested changes

2022-10-03 10:57 UTC, Piumal1999 commented on success_stories/styles.css
> +}
```suggestion
}

```

Add EOF

2022-10-03 10:57 UTC, Piumal1999 commented on success_stories/styles.css
> +    ;
Remove the extra semicolon
```suggestion
    margin-top: 4px;
```

2022-10-04 03:44 UTC, DilinaBandara commented
@Piumal1999 @anjula-sack Can you take a look at this, please?

2022-10-04 08:48 UTC, closed without merging