Edit text-size in mobile view - Success stories page
sef-global/sef-site pull request #1260
Opened 2022-10-06 13:15 UTC by DilinaBandara

## Purpose

The purpose of this PR is to fix #1233 

## Goals

Making the font smaller in mobile view in success stories page

## Approach

Decreasing font size in mobile view by adding media queries

### Screenshots

![image](https://user-images.githubusercontent.com/104125359/194322354-8c8288ce-b8d9-4c63-88b1-9691d7328d8b.png)

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2022-10-06 13:16 UTC, DilinaBandara commented
@anjula-sack @Piumal1999 Can you please review this?

2022-10-06 17:02 UTC, Piumal1999 requested changes

2022-10-06 17:02 UTC, Piumal1999 commented on success_stories/styles.css
>  }
Add EOF
```suggestion
}

```

2022-10-07 16:06 UTC, anjula-sack approved these changes
Thank you! @DilinaBandara

2022-10-07 17:53 UTC, Piumal1999 approved these changes
Good job @DilinaBandara 
Thank you

2022-10-07 17:53 UTC, merged