Fix the alignment of the up speak page's tablet view
sef-global/sef-site pull request #1337
Opened 2022-10-16 11:33 UTC by VishwaAmarasinghe

## Purpose

The purpose of this PR is to fix #1336 

## Goals

To correct the alignment of this page's tablet view .

## Approach

Changed some bootstrap commands.

### Screenshots

![image](https://user-images.githubusercontent.com/90438593/196032998-419b137a-43b1-43fc-887e-72bd8558b08c.png)

  
### Preview Link

https://pr--sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2022-10-16 13:02 UTC, anjula-sack requested changes

2022-10-16 13:02 UTC, anjula-sack commented on upspeak/index.html
> +            <div class="col-lg-5">
We need to keep `col-md-4` as well.
```suggestion
            <div class="col-lg-5 col-md-4">
```

2022-10-16 16:22 UTC, anjula-sack requested changes
`col-lg-5` make it bigger for the desktop view. Try comparing these two,

https://pr-1337-sef-site.surge.sh/upspeak/
https://sefglobal.org/upspeak/

2022-10-17 01:28 UTC, VishwaAmarasinghe commented
If we still use col-md-4 it will be a problem in table view.
![image](https://user-images.githubusercontent.com/90438593/196070438-f53b6587-e32d-42fa-80ba-7feb2b1fcf24.png)

2022-10-17 14:12 UTC, anjula-sack approved these changes
Good job! @VishwaAmarasinghe

2022-10-17 14:12 UTC, merged