Remove white outlines from buttons
sef-global/sef-site pull request #1350
Opened 2022-10-20 16:42 UTC by miniskynet

## Purpose

The purpose of this PR is to fix #1349 

## Goals

Remove design breaking white outlines from 'SEE MORE' and 'LOAD MORE' buttons on One Live pages

## Approach

Remove the class 

### Screenshots

**Now:**
![image](https://user-images.githubusercontent.com/49517852/197007412-257962c1-c1ad-4c5c-b96c-47766fcd67a6.png)
![image](https://user-images.githubusercontent.com/49517852/197008186-b4ddfabf-c232-4631-9e88-55f824236058.png)

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2022-10-20 16:44 UTC, miniskynet commented
@anjula-sack @Piumal1999 I noticed a color change on button click even however. It turns to blue when clicked. Not sure if that should be kept

2022-10-21 14:50 UTC, anjula-sack requested changes

2022-10-21 14:50 UTC, anjula-sack commented on onelive/index.html
> +    <link type="text/css" href="../assets/css/argon.css?v=1.0.1" rel="stylesheet">
Can you remove this duplicated line?

2022-10-21 16:32 UTC, miniskynet commented on onelive/index.html
> +    <link type="text/css" href="../assets/css/argon.css?v=1.0.1" rel="stylesheet">
Done. Seems fine?

2022-10-21 18:35 UTC, anjula-sack commented
@miniskynet can you make this PR ready for review?

2022-10-22 06:50 UTC, anjula-sack approved these changes
Thank you! @miniskynet

2022-10-22 06:50 UTC, merged