Add ScholarX Archive page title
sef-global/sef-site pull request #1422
Opened 2022-11-23 10:34 UTC by YoshithaRathnayake

## Purpose

The purpose of this PR is to fix #1421 

## Goals

Adding ScholarX Archive page title

## Approach

Added ScholarX Archive page title

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

## Related PRs
 

## Learning

2022-11-23 11:27 UTC, anjula-sack requested changes

2022-11-23 11:27 UTC, anjula-sack commented on scholarx/archive/index.html
> +    <title>ScholarX Archive</title>
```suggestion
    <title>ScholarX Archive | Sustainable Education Foundation</title>
```

2022-11-24 16:31 UTC, Piumal1999 approved these changes
Good job @YoshithaRathnayake . Thank you

2022-11-25 02:55 UTC, anjula-sack approved these changes
Thank you! @YoshithaRathnayake

2022-11-25 02:55 UTC, merged