Change the og:image in the engineering team page
sef-global/sef-site pull request #1458
Opened 2022-12-06 02:01 UTC by YoshithaRathnayake

## Purpose

The purpose of this PR is to fix #1451 

## Goals

Changing the og:image in the engineering team page

## Approach

Changed the og:image in the engineering team page

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

## Related PRs
 

## Learning

2022-12-06 15:27 UTC, anjula-sack requested changes

2022-12-06 15:27 UTC, anjula-sack commented on engineering-team.html
> +        <meta property="og:image" content="assets/img/deve-page-hero.png">
Let's rename the image to `engineering-page-hero-image.png`

2022-12-06 15:37 UTC, YoshithaRathnayake commented on engineering-team.html
> +        <meta property="og:image" content="assets/img/deve-page-hero.png">
Sure

2022-12-06 16:14 UTC, YoshithaRathnayake commented on engineering-team.html
> +        <meta property="og:image" content="assets/img/deve-page-hero.png">
Done! @anjula-sack

2022-12-07 16:21 UTC, anjula-sack approved these changes
Thank you!

2022-12-07 16:22 UTC, merged