Implement a modal with mentor/mentee details in ScholarX Archive page
sef-global/sef-site pull request #1459
Opened 2022-12-07 02:51 UTC by YoshithaRathnayake

## Purpose

The purpose of this PR is to fix #1441 

## Goals

Implementing a modal with mentor/mentee details in ScholarX Archive page

## Approach

Implemented a modal with mentor/mentee details in ScholarX Archive page

### Screenshots

This is still preparing
  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/scholarx/archive

##  Checklist
- [ ] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

## Related PRs
 

## Learning

2022-12-10 14:09 UTC, Madhawa97 commented
it's a bit hard to identify what you have actually changed in the code @YoshithaRathnayake. Do you use any code formatting extensions like Prettier?

2022-12-10 14:22 UTC, YoshithaRathnayake commented
> it's a bit hard to identify what you have actually changed in the code @YoshithaRathnayake. Do you use any code formatting extensions like Prettier?

Yeah some because some codes are not aligned correctly, I used SHIFT+ALT+F in vs code to format the code

2022-12-10 14:24 UTC, YoshithaRathnayake commented on scholarx/archive/functions.js
> +
Added from this line

2022-12-10 14:24 UTC, YoshithaRathnayake commented on scholarx/archive/index.html
> +<script type="text/html" id="template-profile-modal-content">
Added from this line

2022-12-10 18:27 UTC, Madhawa97 commented
Well, It's not a good practice to format code. Makes the reviewing lot harder.
Can you undo it?

2022-12-11 02:04 UTC, YoshithaRathnayake commented
> Well, It's not a good practice to format code. Makes the reviewing lot harder.
Can you undo it?

Ok then I will make it on a new pr because I can't undo them

2022-12-11 02:07 UTC, YoshithaRathnayake commented on scholarx/archive/index.html
> +                        <tbody id="mentorProfiles" class="profile-model">
Added a class as profile model

2022-12-11 02:08 UTC, YoshithaRathnayake commented on scholarx/archive/index.html
> +                        <tbody id="menteeProfiles" class="profile-model">
here too

2022-12-11 02:08 UTC, YoshithaRathnayake commented on scholarx/archive/styles.css
> +.profile-model:hover {
Add this css that's it I didn't edit other lines

2022-12-17 11:36 UTC, Madhawa97 commented
You can revert to a previous commit or get the code from a previous commit (before you format) and add your changes again.

2022-12-17 11:58 UTC, YoshithaRathnayake commented
> You can revert to a previous commit or get the code from a previous commit (before you format) and add your changes again.

I'll try

2022-12-21 03:07 UTC, anjula-sack requested changes
can you resolve the conflicts? @YoshithaRathnayake

2022-12-21 05:47 UTC, YoshithaRathnayake commented
> can you resolve the conflicts? @YoshithaRathnayake

@anjula-sack there are lot of conflicts, can you tell me how to resolve them locally?

2022-12-27 16:14 UTC, YoshithaRathnayake commented
> can you resolve the conflicts? @YoshithaRathnayake

Sure @anjula-sack

2022-12-27 16:49 UTC, YoshithaRathnayake commented
@Madhawa97 @anjula-sack Please review this now, @janithlahirukariyawasam helped me to do this

2023-01-19 15:50 UTC, anjula-sack requested changes
can you resolve the conflicts? @YoshithaRathnayake

2023-04-15 10:29 UTC, Piumal1999 commented
@YoshithaRathnayake Thanks for the pull request, but I'm closing this since the requested feature has already been implemented with #1525.

2023-04-15 10:29 UTC, closed without merging