Implement no results message on archive page
sef-global/sef-site pull request #1526
Opened 2023-03-09 16:18 UTC by janithlahirukariyawasam

## Purpose

The purpose of this PR is to fix #1467 

## Goals

The goal of this PR to implement **No Results Found** message

## Approach

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

## Related PRs
 

## Learning

2023-03-11 08:38 UTC, anjula-sack commented on scholarx/archive/styles.css
> +}
```suggestion
}

```

2023-03-11 08:44 UTC, anjula-sack reviewed
@janithlahirukariyawasam can you resolve the conflicts?

2023-03-11 12:04 UTC, anjula-sack requested changes

2023-03-11 12:04 UTC, anjula-sack commented on scholarx/archive/index.html
> +            <div id="noResultsMessage" class="no-results-page" style="display: none;"><img src="no-results-found.png" alt="No Results Found image"></div>
Let's just use a text and font awesome icon. https://fontawesome.com/search?q=search&o=r

2023-03-11 17:43 UTC, janithlahirukariyawasam commented
@anjula-sack Can you check now? also, improve the logic to show no results message when no data is available.

2023-03-12 03:24 UTC, anjula-sack approved these changes
Excellent @janithlahirukariyawasam !

2023-03-12 03:24 UTC, merged