Add skeleton anime to blog posts
sef-global/sef-site pull request #1534
Opened 2023-03-16 15:30 UTC by DilinaBandara

## Purpose

The purpose of this PR is to fix #1495 

## Goals

Add a skeleton loading animation to the blog post section

## Approach

Made an HTML skeleton that displays until the blog posts load

### Screenshots

  
### Preview Link

https://pr-1534-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-03-18 03:40 UTC, anjula-sack requested changes
Good job! @DilinaBandara  Can we add some spacing between the cards? Author name skeleton height also can be reduced.

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/43912578/226083078-9e68d7e0-76e8-43cf-b1cb-3933b1295bb1.png">

2023-03-21 12:52 UTC, anjula-sack requested changes
Spacing issue is still the same @DilinaBandara Let's add some space between the cards.

2023-03-21 13:04 UTC, Piumal1999 commented on engineering-team.html
> +            <div class="col-md-4 mb-5 shadow skeleton-box">
The `shadow` class should be used with the card, not the column. That will fix the spacing issue. And you will have to resize the skeleton elements.

Also please remove the unused CSS classes (Because, classes like `skeleton-post-body`, `skeleton-author` don't have any CSS styles)

2023-03-25 10:49 UTC, DilinaBandara commented
Can you please have a look @Piumal1999 @anjula-sack, apologies for the delay

2023-03-25 11:08 UTC, Piumal1999 commented
<img width="358" alt="image" src="https://user-images.githubusercontent.com/27498587/227713907-be992cd6-be8d-4b3a-bc58-2c8a261c61c3.png">

Now it doesn't show the skeleton for the author section (profile image + name). Can we include that as well?

2023-03-25 13:04 UTC, anjula-sack requested changes

2023-03-25 13:04 UTC, anjula-sack commented on engineering-team.css
> +}
```suggestion
}

```

2023-03-25 13:04 UTC, anjula-sack commented on engineering-team.css
> +}
Add the end of line

2023-03-26 02:27 UTC, anjula-sack approved these changes
Good job! @DilinaBandara

2023-03-26 02:27 UTC, merged