Update homepage testimonial section
sef-global/sef-site pull request #1578
Opened 2023-05-20 05:41 UTC by gajindubandara

## Purpose

The purpose of this PR is to fix #1577

## Goals
To update the home page testimonial section
## Approach
Updated the home page testimonials & card styles

### Screenshots
![image](https://github.com/sef-global/sef-site/assets/63200586/4eb8a34a-8c3f-4483-a4c8-34ec4bbfa7c5)  

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-05-20 05:47 UTC, gajindubandara commented
Note -
1. The designations of Ramith and Nayanathara are not added yet (I'll update it)
2. There is a CSS section used for the old testimonial styles in the `global-custom` file. Previously it was used for the home page testimonials and the upspeak page testimonial, shall we remove that old CSS section and update the upspeak page testimonial the same as the new home page testimonial section

2023-05-20 08:02 UTC, YoshithaRathnayake requested changes
@gajindubandara this should be the preview link right? 
- https://pr-1578-sef-site.surge.sh/
Can you change it?

2023-05-20 08:03 UTC, gajindubandara commented
> @gajindubandara this should be the preview link right? 
> - https://pr-1578-sef-site.surge.sh/
> 
> Can you change it?

Done!

2023-06-16 14:40 UTC, anjula-sack requested changes

2023-06-16 14:40 UTC, anjula-sack commented on index.html
> +                        </p>
Let's remove Sanmugathasan Prasanthan from here @gajindubandara

2023-06-16 23:50 UTC, YoshithaRathnayake requested changes

2023-06-16 23:50 UTC, YoshithaRathnayake commented on index.html
> +
Is this line required? @gajindubandara 
```suggestion
```

2023-06-17 07:49 UTC, YoshithaRathnayake requested changes

2023-06-17 07:49 UTC, YoshithaRathnayake commented on assets/css/global-custom.css
> +
Is this line also required? @gajindubandara 
If not needed,
```suggestion
```

2023-06-17 13:32 UTC, YoshithaRathnayake commented on assets/css/global-custom.css
> +
Oh sorry @gajindubandara we need that line. That is the end of the line, please add it again, sorry for the inconvenience

![image](https://github.com/sef-global/sef-site/assets/97069900/79558abf-40de-44b3-bde7-3cad341eb5cc)

2023-06-17 13:33 UTC, YoshithaRathnayake requested changes

2023-06-17 13:33 UTC, YoshithaRathnayake commented on assets/css/global-custom.css
> +}
```suggestion
}

```

2023-06-17 13:34 UTC, YoshithaRathnayake commented on assets/css/global-custom.css
> +
See below I have suggested the changes. Commit them @gajindubandara

2024-01-06 13:20 UTC, closed without merging