Link the ScholarX Archive Page to the ScholarX 23 Page
sef-global/sef-site pull request #1581
Opened 2023-05-27 15:15 UTC by YoshithaRathnayake

## Purpose

The purpose of this PR is to fix #1551 

## Goals

Linking the ScholarX Archive Page to the ScholarX 23 Page

## Approach

I linked the ScholarX Archive Page to the ScholarX 23 Page

### Screenshots

![image](https://github.com/sef-global/sef-site/assets/97069900/26869212-e816-428e-a9d2-47f08d5dc949)

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

## Related PRs
 

## Learning

2023-05-29 17:12 UTC, anjula-sack requested changes

2023-05-29 17:12 UTC, anjula-sack commented on scholarx/2023/index.html
> +        <h1 class="mb-0 text-onelive">Explore The Unveiling</h1>
```suggestion
        <h1 class="mb-0 text-onelive">Checkout our past mentors and mentees</h1>
```

2023-05-30 01:43 UTC, anjula-sack requested changes

2023-05-30 01:43 UTC, anjula-sack commented on scholarx/2023/index.html
> +        <p class="display-3 text-onelive font-weight-bolder">ScholarX Archive</p>
```suggestion
        <p class="display-3 text-onelive font-weight-bolder">Checkout our past mentors and mentees</p>
```

2023-05-30 01:43 UTC, anjula-sack commented on scholarx/2023/index.html
> +        <p class="display-3 text-onelive font-weight-bolder">ScholarX Archive</p>
We don't need to mention archive part twice

2023-05-31 01:38 UTC, anjula-sack requested changes
Let's break the title into two parts
<img width="877" alt="image" src="https://github.com/sef-global/sef-site/assets/43912578/5821d0e1-a1ff-4c2d-9111-0e8c29b01ed6">

just like in this section
<img width="522" alt="image" src="https://github.com/sef-global/sef-site/assets/43912578/cc67ce6f-6188-482f-9e62-685777a3ba31">

2023-06-01 00:01 UTC, YoshithaRathnayake commented
@anjula-sack how about now?

2023-06-01 02:05 UTC, anjula-sack approved these changes
Good job! @YoshithaRathnayake

2023-06-01 02:05 UTC, merged