Setting counting feature on projects section
sef-global/sef-site pull request #1630
Opened 2024-05-16 17:51 UTC by RamithaHeshan33

## Purpose

The purpose of this PR is to fix #1629

## Goals

Setting the counting feature on our projects section

## Approach

update the index.html file

### Screenshots

Before fixing the issue

![before](https://github.com/sef-global/sef-site/assets/142712365/d647a266-bae8-46f2-807c-d65b17b091ae)

After fixing the issue

https://github.com/sef-global/sef-site/assets/142712365/b8e175b3-4ca5-4417-b8d9-e7cc9107d20f

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] I have read and understood the [development best practices](https://handbook.sefglobal.org/organisation/engineering-team#development-best-practices) guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2024-05-16 18:22 UTC, YoshithaRathnayake requested changes

2024-05-16 18:22 UTC, YoshithaRathnayake commented on index.html
> +		            <a href="onelive" class="card col-lg-4 shadow project-card">
```suggestion
		    <a href="onelive" class="card col-lg-4 shadow project-card">
```
```

2024-05-17 02:23 UTC, RamithaHeshan33 commented
@YoshithaRathnayake can you check if this PR is ok now please?

2024-05-18 05:46 UTC, YoshithaRathnayake requested changes, later dismissed

2024-05-18 05:46 UTC, YoshithaRathnayake commented on index.html
> +		        <a href="onelive" class="card col-lg-4 shadow project-card">
Can you remove this space? @RamithaHeshan33 its not still removed, it should be like the line 158

2024-05-18 06:59 UTC, RamithaHeshan33 commented
I think it's ok now. @YoshithaRathnayake

2024-05-18 13:43 UTC, YoshithaRathnayake commented
> I think it's ok now. @YoshithaRathnayake

@anjula-sack will review this! @RamithaHeshan33

2024-05-18 13:56 UTC, YoshithaRathnayake commented
After this PR there is an error when click the scholarx card and again undo (return immediately before it redirects for the scholarx page) the scholarx logo of the card is hidden and the card's height is getting longer

2024-05-19 18:05 UTC, anjula-sack approved these changes
This is amazing! @RamithaHeshan33 Good job!

2024-05-19 18:09 UTC, merged