Create basic structure for scholarX landing page
sef-global/sef-site pull request #265
Opened 2019-11-10 11:41 UTC by Gravewalker666

## Purpose
> Creating new flat UI design for the scholarX page

## Goals
> Developing design according to the design provided

## Approach
> Developing the web page in html using bootstrap

## Security checks
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Related PRs
> N/A

## Test environment
> java 1.8, ubuntu 19.04, chrome, apache
 
## Learning
> N/A

2019-11-10 12:40 UTC, jayasanka-sack commented on src/main/webapp/onelive.html
> +    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
Remove this if using Montserrat

2019-11-10 12:44 UTC, jayasanka-sack commented on src/main/webapp/onelive.html
> +    </div>
Remove unwanted blank space.

Remove unwanted space.
```suggestion
<div id="navbar"></div>
```

2019-11-10 12:49 UTC, jayasanka-sack requested changes
Add screenshots

2019-11-10 12:49 UTC, jayasanka-sack commented on src/main/webapp/onelive.html
> +
Remove unwanted blank space.

2019-11-10 12:49 UTC, jayasanka-sack commented on src/main/webapp/onelive.html
> +
Remove unwanted blank space.

2019-11-10 12:49 UTC, jayasanka-sack commented on src/main/webapp/onelive.html
> +        // link to the navbar, footer content goes here
Unwanted comment line

2019-11-10 12:49 UTC, jayasanka-sack commented on src/main/webapp/scholarx.html
> +                                        >
```
 <div id="collapseTwo"
      class="collapse"
      aria-labelledby="headingTwo"
      data-parent="#accordionExample">
```

2019-11-10 12:49 UTC, jayasanka-sack commented on src/main/webapp/scholarx.html
> +                                        >
Change other places too

2019-11-12 14:35 UTC, jayasanka-sack commented
#236

2019-11-13 14:57 UTC, Gravewalker666 commented
![screencapture-localhost-63342-sef-site-src-main-webapp-team-html-2019-11-13-20_23_49](https://user-images.githubusercontent.com/45477334/68774749-96c88f80-0653-11ea-9726-ca2c05a388f1.png)

2019-11-13 15:10 UTC, Gravewalker666 commented
#275 
#276

2019-11-13 15:12 UTC, Gravewalker666 commented
#248

2019-11-13 15:15 UTC, Gravewalker666 reviewed
Done

2019-11-13 15:23 UTC, Gravewalker666 reviewed
Done

2019-11-13 15:48 UTC, jayasanka-sack commented
Thanks @Gravewalker666 !

2019-11-13 15:48 UTC, merged

2020-01-09 13:32 UTC, jayasanka-sack commented
#236, #275, #276 #248 #265