Add animation for loading more profile cards
sef-global/sef-site pull request #280
Opened 2019-12-11 18:56 UTC by Piumal1999

## Purpose

To add an animation to load profile cards when the "See more" button on the team page is clicked.
Issue #279 

## Goals
Added a fade in animation for the cards

## Approach
JQuery and AJAX were used to add the animation.

### Screenshots
N/A
  
### Preview Link
https://piumal1999.github.io/sef-site/src/main/webapp/examples/team.html

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
 
JDK 1.8, Ubuntu 19.04, Google Chrome

## Learning
Used Stackoverflow and W3Schools pages

2019-12-12 06:14 UTC, jayasanka-sack requested changes

2019-12-12 06:14 UTC, jayasanka-sack commented on src/main/webapp/examples/team.html
> +
Remove Whitespaces

2019-12-12 06:14 UTC, jayasanka-sack commented on src/main/webapp/examples/team.html
Remove whitespaces

2019-12-13 14:01 UTC, Piumal1999 commented on src/main/webapp/examples/team.html
> +
done

2019-12-13 14:01 UTC, Piumal1999 commented on src/main/webapp/examples/team.html
done

2019-12-13 14:28 UTC, merged

2019-12-13 14:29 UTC, jayasanka-sack commented
Merged.