modifed students,experts,volunteers section in home page
sef-global/sef-site pull request #386
Opened 2020-01-16 14:35 UTC by yohanym95

## Purpose

The purpose of this PR is to fix #325 

## Goals

Modify Students/Experts section

## Approach

Removed unnecessary paragraph sections and add them into single paragraph.
Apply CSS style into paragraph. 

### Screenshots

  
![s1](https://user-images.githubusercontent.com/31344335/72533546-5ed00980-389b-11ea-82de-3650857f3638.JPG)
![s2](https://user-images.githubusercontent.com/31344335/72533548-5ed00980-389b-11ea-8853-8285812598de.JPG)
![s3](https://user-images.githubusercontent.com/31344335/72533549-5f68a000-389b-11ea-8347-109bdccd108a.JPG)

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 
Windows 10, Google Chrome

## Learning

N/A

2020-01-16 14:40 UTC, jayasanka-sack requested changes
It should be similar to the provided design, colors, borders, Font sizes etc..

2020-01-16 15:10 UTC, yohanym95 commented
@jayasanka-sack  how is it about now?

2020-01-16 18:22 UTC, jayasanka-sack commented
> Sould be similar to the provided design, colors, borders, Font sizes etc..
@yohanym95

2020-01-17 06:16 UTC, yohanym95 commented
@jayasanka-sack how is it about now?

2020-01-18 02:38 UTC, Gravewalker666 requested changes
Great Job! @yohanym95 
Set text alignment on the card to justify

2020-01-18 02:59 UTC, jayasanka-sack requested changes

2020-01-18 02:59 UTC, jayasanka-sack commented on src/main/webapp/assets/css/global-custom.css
> +a.nav-link.mb-sm-3.mb-md-0.py-3.active{
The selector names look a little bit messy.
@Gravewalker666, Please suggest good selectors & suggest a way to optimize these rules.

2020-01-18 02:59 UTC, jayasanka-sack commented on src/main/webapp/index.html
> +                                    <span class="display-4 py-2 px-3 text-uppercase text-roboto" style="font-size: 20px;">students</span>
Avoid using inline CSS rules

2020-01-18 10:45 UTC, yohanym95 commented on src/main/webapp/index.html
> +                                    <span class="display-4 py-2 px-3 text-uppercase text-roboto" style="font-size: 20px;">students</span>
i'll fix it.

2020-01-18 14:46 UTC, Gravewalker666 commented
@yohanym95 Thank you!
You have done all the hard work to complete the issue. There are only some minor changes we need to do to complete it fully. Since we have to publish the site by morrow I will merge this and get on with it.
Cheers mate!

2020-01-18 14:47 UTC, merged