Create an empty profile modal for mentors
sef-global/sef-site pull request #546
Opened 2020-02-27 15:48 UTC by anjula-sack

## Purpose

- The purpose of this PR is to fix #541 

## Goals

- Create an empty profile modal for mentors

## Approach

- Added an empty modal.
- Remove the LinkedIn button from the current card. 

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2020-02-27 16:31 UTC, jayasanka-sack requested changes
- the cursor should change to `pointer` when hovering

2020-02-27 16:31 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> +                </div>
Take this out from the moustache template. 
Place it at the end of the body.

2020-02-28 02:37 UTC, anjula-sack commented
Changes are applied.

2020-02-28 06:09 UTC, jayasanka-sack submitted a review, later dismissed

2020-02-28 06:09 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> +                         data-toggle="modal" data-target="#profileModal" style="cursor: pointer"
write a custom CSS rule to change the cursor

ex: 

```
.hover-profile-card .img {
    cursor: pointer;
}
```

2020-02-28 06:14 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> +                         data-toggle="modal" data-target="#profileModal" style="cursor: pointer"
Usually, we do not use inline CSS

2020-02-28 06:39 UTC, anjula-sack commented on src/main/webapp/scholarx/2020/index.html
> +                         data-toggle="modal" data-target="#profileModal" style="cursor: pointer"
on it.

2020-02-28 14:58 UTC, Gravewalker666 approved these changes

2020-02-28 14:59 UTC, Gravewalker666 approved these changes

2020-02-28 15:51 UTC, merged