add apply button to hero section
sef-global/sef-site pull request #560
Opened 2020-02-29 11:28 UTC by 99sumedha

## Purpose
The purpose of this PR is to fix #558 
Move the page to the apply section when clicked
## Goals

Now a user can easily move to the apply section straight forward

## Approach

Add an id to the apply section and link it to the button in the hero section

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2020-02-29 11:48 UTC, jayasanka-sack requested changes
Please remove `class="pb-5"`  on line number 45.
```
<p class="pb-5">ScholarX is an exclusive 6-month program aimed at providing
                            mentoring support to a selected pool of ...
```

2020-02-29 11:48 UTC, jayasanka-sack commented on src/main/webapp/scholarx/archive/2019/index.html
>      </div>
Do not change other files

2020-03-01 03:41 UTC, 99sumedha commented
class="pb-5" class removed

2020-03-01 03:50 UTC, jayasanka-sack requested changes

2020-03-01 03:50 UTC, jayasanka-sack commented on src/main/webapp/scholarx/archive/2019/index.html
>      </div>
@99sumedha Do not change this file. We need the ally button only for 2020 page

2020-03-01 09:05 UTC, 99sumedha commented
New commit added

2020-03-01 09:54 UTC, jayasanka-sack requested changes

2020-03-01 09:54 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> -        <div class="row justify-content-center">
Do not remove this line

2020-03-01 09:58 UTC, jayasanka-sack requested changes

2020-03-01 09:58 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> +        <div id="teamContent"></div>
What is this?

2020-03-01 10:30 UTC, jayasanka-sack requested changes

2020-03-01 10:30 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> -        <div id="teamContent"></div>
do not remove this line

2020-03-01 10:33 UTC, anjula-sack requested changes
Remove <<<<<<< HEAD
======= and >>>>>>> 19d1d643772e7487696ef0592233b54f0be664c6

2020-03-01 11:03 UTC, jayasanka-sack requested changes

2020-03-01 11:03 UTC, jayasanka-sack commented on src/main/webapp/scholarx/2020/index.html
> +
Remove this whitespace

2020-03-01 11:51 UTC, 99sumedha commented on src/main/webapp/scholarx/2020/index.html
> +
Done

2020-03-01 12:12 UTC, jayasanka-sack commented
Closing since we have to merge scholarx-2020 branch

2020-03-01 12:12 UTC, closed without merging