Solve faq button bug
sef-global/sef-site pull request #602
Opened 2020-03-15 08:05 UTC by Gravewalker666

## Purpose
The purpose of this PR is to fix #587 

## Goals
The goal is to solve the issue on faq component

## Approach
Removing type attribute from the faq question

### Screenshots
![image](https://user-images.githubusercontent.com/45477334/76697792-a7504b80-66c1-11ea-8cc2-6cc3611cdaac.png)

  
### Preview Link

https://pr-602-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
N/A 

## Test environment
Google Chrome, Opera, Firefox
Ubuntu 19.04

## Learning
N/A

2020-03-15 08:06 UTC, Gravewalker666 commented
@Piumal1999 Please Review this PR from your environment.

2020-03-15 08:26 UTC, Piumal1999 requested changes
Great! The bug is fixed in this pr.
But the plus/minus sign doesn't change when clicked. I'll attach a screenshot.
![ScholarX_Sustainable_Education_Foundation_-_2020-03-15_13 54 37](https://user-images.githubusercontent.com/27498587/76698082-9b19bd80-66c4-11ea-865d-dd5e6d7fa06e.png)

2020-03-17 05:52 UTC, Gravewalker666 commented
@Piumal1999 I checked from different browsers and devices but the plus/minus function works fine for me. Can you check it out again?

2020-03-17 16:53 UTC, jayasanka-sack commented
Ahaha! `type="button"` was the guy behind the mask 😅

![image](https://user-images.githubusercontent.com/33048395/76880563-d7ecdc80-689d-11ea-87a9-36612b81295b.png)

2020-03-17 18:41 UTC, Piumal1999 commented
> @Piumal1999 I checked from different browsers and devices but the plus/minus function works fine for me. Can you check it out again?

Ah yes. It is working now!! Sorry for the inconvenience.

2020-03-17 18:44 UTC, Piumal1999 approved these changes

2020-03-18 02:32 UTC, anjula-sack approved these changes
Awesome!

2020-03-18 02:36 UTC, merged