Update scholarX 2020 mentors details
sef-global/sef-site pull request #615
Opened 2020-03-19 13:32 UTC by anjula-sack

## Purpose

- The purpose of this PR is to fix #614 

## Goals

- Update scholarX 2020 mentors details

## Approach

- Update the `mentors.json` file using given details.
  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2020-03-19 13:34 UTC, Gravewalker666 approved these changes
Great job @anjula-sack

2020-03-20 11:08 UTC, jayasanka-sack requested changes
Nishantha Rajakaruna's website button is not rendered properly.

![Screenshot 2020-03-20 at 16 39 28](https://user-images.githubusercontent.com/33048395/77158461-61ccbd80-6ac9-11ea-9568-416bf5b686fb.jpg)

cc: @Gravewalker666 @Piumal1999

2020-03-20 15:13 UTC, Gravewalker666 requested changes

2020-03-20 15:13 UTC, Gravewalker666 commented on src/main/webapp/scholarx/2020/mentors.json
> +        "icon" : "fa-globe",
- `<i class="fas fa-globe"></i>`
This is the full HTML line for the globe icon. I think the issue is that `fas` class at the beginning is not the one in the template.

2020-03-20 16:47 UTC, Gravewalker666 submitted a review, later dismissed

2020-03-21 03:52 UTC, jayasanka-sack commented
The button is still invisible. Only the icon is there.

Please go through the template first.
1. 
 https://github.com/sef-global/sef-site/blob/4f5320033dba376a762114727745bccb2175d469/src/main/webapp/scholarx/2020/index.html#L628

the key `platform` is to render the necessary CSS class for the button.
The value `website` becomes `btn-website` but, there's no such a class defined. Just go through available btn classes and add a one. 

2. 
https://github.com/sef-global/sef-site/blob/4f5320033dba376a762114727745bccb2175d469/src/main/webapp/scholarx/2020/index.html#L629

The icon loads this way.  `fas fa-globe` becomes `<i class="fab fas fa-globe"></i>` which isn't nice.

Please edit the template as `<i class="{{icon}}"></i>` and modify all the icon keys' values with the prefix.

ex: 
```
{
...
"icon" : "fab fa-facebook",
...
}
```

2020-03-21 05:17 UTC, jayasanka-sack approved these changes
LGTM

2020-03-21 05:23 UTC, Gravewalker666 approved these changes

2020-03-21 06:20 UTC, merged