Create a script to load videos from youtube API
sef-global/sef-site pull request #628
Opened 2020-03-27 15:47 UTC by anjula-sack

## Purpose

- The purpose of this PR is to fix #627 

## Goals

- Create a script to load videos from youtube API

## Approach

- Write a script to load items from the url.

### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/onelive/archive

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2020-03-27 15:54 UTC, jayasanka-sack commented on src/main/webapp/onelive/archive/index.html
> +        });
Remove extra spaces. Format it properly. 
Add meaningful ids. :)

2020-03-27 17:04 UTC, Piumal1999 requested changes
Nice!!
It is good if we can keep the CSS file in the main assets/css directory. 
And also format the code.

2020-03-27 17:04 UTC, Piumal1999 commented on src/main/webapp/onelive/archive/index.html
>      </section>
Do we need this section?

2020-03-27 17:07 UTC, jayasanka-sack commented
> It is good if we can keep the CSS file in the main assets/css directory.

@Piumal1999 It has been changed with the new file structure. If a page using custom styles that are used by only that page, has to be in the same directory.

2020-03-27 17:09 UTC, jayasanka-sack commented on src/main/webapp/onelive/archive/index.html
> +    {{/data}}
Remove this section because the logic isn't implemented.

2020-03-27 17:23 UTC, Piumal1999 commented
>
> @Piumal1999 It has been changed with the new file structure. If a page using custom styles that are used by only that page, has to be in the same directory.
> 

Ah ok. :grinning:

2020-03-28 05:29 UTC, anjula-sack commented on src/main/webapp/onelive/archive/index.html
>      </section>
no my bad

2020-03-28 06:31 UTC, Piumal1999 approved these changes

2020-03-28 07:21 UTC, merged

2020-03-28 11:04 UTC, jayasanka-sack commented on src/main/webapp/onelive/archive/index.html
> +                $('#youtube-video').html(renderedData);
videos