Create a component to display upcoming events
sef-global/sef-site pull request #635
Opened 2020-04-02 15:19 UTC by Piumal1999

## Purpose

The purpose of this PR is to fix #634 

## Goals

To create a component to display the upcoming event

## Approach

Created a component using cards and added custom CSS for that

### Screenshots

![SEF_site_Components_-_2020-04-02_20 47 47](https://user-images.githubusercontent.com/27498587/78266308-4038f080-7523-11ea-9bf7-d7dd0c7ac435.png)

  
### Preview Link

https://pr-635-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
Google Chrome

## Learning

N/A

2020-04-02 16:04 UTC, jayasanka-sack requested changes
Solid design! 😍🔥

Just fix these two minor changes

2020-04-02 16:04 UTC, jayasanka-sack commented on src/main/webapp/assets/css/global-custom.css
> +
Remove this space

2020-04-02 16:04 UTC, jayasanka-sack commented on src/main/webapp/examples/components.html
> +            </div>
This should be in another row right?

2020-04-02 16:30 UTC, Piumal1999 commented on src/main/webapp/examples/components.html
> +            </div>
Oh yes😁

2020-04-02 16:38 UTC, Piumal1999 commented on src/main/webapp/examples/components.html
> +            </div>
fixed

2020-04-03 12:20 UTC, jayasanka-sack approved these changes
Thanks @Piumal1999! 
I love this design! 🔥

2020-04-03 14:10 UTC, anjula-sack approved these changes
Awesome! @Piumal1999

2020-04-03 14:11 UTC, merged