Add Google Analytics tag to the pages
sef-global/sef-site pull request #700
Opened 2020-05-28 12:01 UTC by Piumal1999

## Purpose

The purpose of this PR is to fix #699

## Goals

Adding google analytics to sef-site

## Approach

Added the google analytics tag to all pages

### Screenshots

N/A

### Preview Link

https://pr-700-sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
N/A

## Learning

https://support.google.com/analytics/answer/1008015?hl=en

2020-05-28 13:01 UTC, anjula-sack submitted a review, later dismissed

2020-05-28 13:43 UTC, jayasanka-sack requested changes
Nice job @Piumal1999 !

Could you please remove those whitespace?

2020-05-28 13:43 UTC, jayasanka-sack commented on src/main/webapp/apply.html
> +
Remove this white space

2020-05-28 13:43 UTC, jayasanka-sack commented on src/main/webapp/apply.html
> +
Remove this white space

2020-05-28 13:43 UTC, jayasanka-sack commented on src/main/webapp/apply.html
> +
Remove this white space

2020-05-28 15:28 UTC, Piumal1999 commented on src/main/webapp/apply.html
> +
Done

2020-05-28 15:28 UTC, Piumal1999 commented
Removed whitespaces

2020-05-29 13:24 UTC, jayasanka-sack approved these changes
Thanks @Piumal1999 !

2020-05-29 13:38 UTC, anjula-sack approved these changes
Awesome! @Piumal1999  👏

2020-05-29 13:38 UTC, merged