Update sef-team with available members
sef-global/sef-site pull request #704
Opened 2020-06-02 17:13 UTC by Gimhan-minion

## Purpose
The purpose of this PR is to fix #703 

## Goals
To update sef team with active members.

## Approach
Add and remove the necessary members 
  
### Preview Link
https://pr--sef-site.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-06-02 22:10 UTC, akshika47 submitted a review, later dismissed

2020-06-03 07:25 UTC, anjula-sack commented on src/main/webapp/assets/content/json/team.json
> -      "image": "hasitha.jpg",
Remove the image too.

2020-06-03 07:28 UTC, anjula-sack requested changes
Remove `hasitha.jpg` from the files.

2020-06-03 08:20 UTC, Gimhan-minion commented on src/main/webapp/assets/content/json/team.json
> -      "image": "hasitha.jpg",
Done

2020-06-03 08:21 UTC, anjula-sack approved these changes
Thank you! 😊 @Gimhan-minion

2020-06-03 13:04 UTC, jayasanka-sack approved these changes
Thanks @Gimhan-minion !

2020-06-03 13:04 UTC, merged