Update irc file and images
sef-global/sef-site pull request #879
Opened 2021-02-26 16:07 UTC by nejawittatchy

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-02-27 13:38 UTC, Gimhan-minion requested changes
@nejawittatchy Good Job! I guess you missed the LinkedIn links. Can you update them too as in the issue #868?

2021-02-27 13:53 UTC, anjula-sack commented on assets/content/json/irc.json
> +    "image": "arosha.jpeg",
name and the name of the image is different

2021-02-27 13:54 UTC, anjula-sack commented on assets/content/json/irc.json
> +
Remove this line

2021-02-27 13:55 UTC, anjula-sack requested changes

2021-02-27 13:55 UTC, anjula-sack commented on assets/content/json/irc.json
> +    "description": "Psycohlogy",
Check the spellings

2021-02-28 13:50 UTC, Gimhan-minion approved these changes

2021-02-28 13:52 UTC, anjula-sack approved these changes
Awesome! @nejawittatchy

2021-02-28 13:52 UTC, merged