Create team members' LinkedIn profiles direct to a new tab.
sef-global/sef-site pull request #964
Opened 2021-06-07 12:58 UTC by pasindur99

## Purpose
The issue is related to the team members' LinkedIn profiles load in the same tab.

## Goals
Create team members' LinkedIn profiles direct to a new tab.

## Approach

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-sef-site.surge.sh/

##  Checklist
- [X] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [X] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-06-16 05:39 UTC, Gravewalker666 requested changes
Thank you @pasindur99 
Can we change the PR title and commit message into something more meaningful? 
It should describe what you have done clearly and simply 🙂

2021-06-17 04:42 UTC, pasindur99 commented
okay @Gravewalker666 I will.

2021-06-17 05:17 UTC, janethavi requested changes
Can we have this feature to the profile image as well? Because when the image is clicked instead of the LinkedIn logo the profile will be loaded on the same tab.

2021-06-18 18:16 UTC, janethavi approved these changes

2021-06-20 07:06 UTC, Gimhan-minion approved these changes

2021-06-20 07:08 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @pasindur99 !

2021-06-20 07:20 UTC, Gravewalker666 approved these changes

2021-06-20 07:22 UTC, merged